equipe/urls.py
from django.urls import path
from .views import equipe_list, equipe_create, equipe_update, equipe_delete, equipe_detail, candidatura_equipe
from .views_funcao import *
from .views_lideranca import *
from .views_membros import *
from .views_escala import *
from .views_pdf import *

urlpatterns = [
    path('', equipe_list, name='equipe_list'),
    path('create/', equipe_create, name='equipe_create'),
    path('<int:pk>/', equipe_detail, name='equipe_detail'),
    path('<int:pk>/edit/', equipe_update, name='equipe_update'),
    path('<int:pk>/delete/', equipe_delete, name='equipe_delete'),
    path('candidatura/', candidatura_equipe, name='processar_candidatura'),

    
    # funcao
    path('<int:equipe_pk>/funcoes/', funcao_list, name='listar_funcoes'),
    path('<int:equipe_pk>/funcoes/<int:pk>/', funcao_detail, name='funcao_detail'),
    path('<int:equipe_pk>/funcoes/adicionar/', funcao_create, name='funcao_create'),
    path('<int:equipe_pk>/funcao/<int:pk>/editar/', funcao_update, name='funcao_update'),
    path('<int:equipe_pk>/funcao/<int:pk>/excluir/', funcao_delete, name='funcao_delete'),
    
    #lideranca
    path('<int:equipe_pk>/liderancas/', lideranca_list, name='listar_liderancas'),
    path('lideranca/<int:pk>/', lideranca_detail, name='lideranca_detail'),
    path('<int:equipe_pk>/lideranca/adicionar/', lideranca_create, name='lideranca_create'),
    path('lideranca/<int:pk>/editar/', lideranca_update, name='lideranca_update'),
    path('lideranca/<int:pk>/excluir/', lideranca_delete, name='lideranca_delete'),
    
    #membros
    path('<int:equipe_pk>/membros/', membros_equipe_list, name='listar_membros_equipe'),
    path('<int:equipe_pk>/membro/<int:pk>/', membros_equipe_detail, name='membros_equipe_detail'),
    path('<int:equipe_pk>/membro/adicionar/', membros_equipe_create, name='membros_equipe_create'),
    path('<int:equipe_pk>/membro/<int:pk>/editar/', membros_equipe_update, name='membros_equipe_update'),
    path('<int:equipe_pk>/membro/<int:pk>/excluir/', membros_equipe_delete, name='membros_equipe_delete'),

    path('<int:equipe_pk>/escalas/', listar_escalas, name='listar_escalas'),
    path('<int:equipe_pk>/escalas/<int:pk>', escala_detail_equipe, name='escala_detail_equipe'),

    path('equipe/<int:equipe_pk>/escalas/exportar-pdf/', exportar_tabela_para_pdf, name='exportar_pdf'),
    
    path('equipe/<int:equipe_pk>/membros-pendentes/', listar_membros_pendentes, name='listar_membros_pendentes'),
    path('equipe/<int:equipe_pk>/aprovar-membro/<int:membro_pk>/', aprovar_membro, name='aprovar_membro'),
    path('equipe/<int:equipe_pk>/rejeitar-membro/<int:membro_pk>/', rejeitar_membro, name='rejeitar_membro'),


]

escalaconnect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView, LoginView

from .views import base_view, calendario_view, redirect_to_home
from escala.views2 import carregar_funcoes

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(template_name='login.html', next_page='/'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),

    path('', base_view, name='base_page'),
    path('calendario/', calendario_view, name='calendario'),

    path('api/escala/', include('escala.urls')),
    path('api/equip/', include('equipe.urls')),
    path('api/events/', include('evento.urls')),
    path('api/user/', include('usuario.urls')),
    path('api/plan/', include('planejamento.urls')),
    path('api/busy/', include('ocupado.urls')),
    path('api/free/', include('disponivel.urls')),
    
    path('api/carregar_funcoes/', carregar_funcoes, name='carregar_funcoes'),


]

handler404 = 'escalaconnect.views.redirect_to_home'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

planejamento/urls.py
from django.urls import path
from .views import (
    planejamento_list, planejamento_create, planejamento_update,
    planejamento_delete, planejamento_detail
)

urlpatterns = [
    path('', planejamento_list, name='planejamento_list'),
    path('adicionar/', planejamento_create, name='planejamento_create'),
    path('<int:pk>/editar/', planejamento_update, name='planejamento_update'),
    path('<int:pk>/excluir/', planejamento_delete, name='planejamento_delete'),
    path('<int:pk>/', planejamento_detail, name='planejamento_detail'),
]

planejamento/models.py
from django.db import models
from django.utils.timezone import now
from escala.models import Funcao

class Planejamento(models.Model):
    nome = models.CharField(max_length=255)
    data_cadastro = models.DateTimeField(default=now)
    data_atualizacao = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nome

class PlanejamentoFuncao(models.Model):
    planejamento = models.ForeignKey(Planejamento, on_delete=models.CASCADE, related_name="funcoes")
    funcao = models.ForeignKey(Funcao, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.planejamento.nome} - {self.funcao.nome}"

planejamento/forms.py
from django import forms
from .models import Planejamento, PlanejamentoFuncao
from escala.models import Funcao

class PlanejamentoForm(forms.ModelForm):
    class Meta:
        model = Planejamento
        fields = ['nome']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
        }

class PlanejamentoFuncaoForm(forms.ModelForm):
    class Meta:
        model = PlanejamentoFuncao
        fields = ['funcao']

    def __init__(self, *args, **kwargs):
        planejamento = kwargs.pop('planejamento', None)
        super(PlanejamentoFuncaoForm, self).__init__(*args, **kwargs)

        if planejamento:
            self.fields['funcao'].queryset = Funcao.objects.filter(equipe__isnull=False)

planejamento/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.core.paginator import Paginator
from .models import Planejamento, PlanejamentoFuncao
from .forms import PlanejamentoForm, PlanejamentoFuncaoForm
from django.forms import modelformset_factory
from escala.models import Funcao

def planejamento_list(request):
    query = request.GET.get('q', '')
    planejamentos = Planejamento.objects.filter(nome__icontains=query).order_by('-data_cadastro')

    paginator = Paginator(planejamentos, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'planejamento/planejamento_list.html', {'page_obj': page_obj, 'query': query})


def planejamento_create(request):
    planejamento = None
    if request.method == "POST":
        form = PlanejamentoForm(request.POST)
        funcao_formset = modelformset_factory(PlanejamentoFuncao, form=PlanejamentoFuncaoForm, extra=1)(request.POST)

        if form.is_valid() and funcao_formset.is_valid():
            planejamento = form.save()

            for funcao_form in funcao_formset:
                if funcao_form.cleaned_data:
                    funcao = funcao_form.save(commit=False)
                    funcao.planejamento = planejamento
                    funcao.save()

            return redirect('planejamento_list')
    else:
        form = PlanejamentoForm()
        funcao_formset = modelformset_factory(PlanejamentoFuncao, form=PlanejamentoFuncaoForm, extra=1)()

    context = {
        'form': form,
        'formset': funcao_formset,
        'funcoes_disponiveis': Funcao.objects.all(),
    }
    return render(request, 'planejamento/planejamento_form.html', context)


# def planejamento_create(request):
#     if request.method == 'POST':
#         form = PlanejamentoForm(request.POST)
#         if form.is_valid():
#             planejamento = form.save()
#             return redirect('planejamento_list')
#     else:
#         form = PlanejamentoForm()

#     return render(request, 'planejamento/planejamento_form.html', {'form': form})

def planejamento_update(request, pk):
    planejamento = get_object_or_404(Planejamento, pk=pk)

    if request.method == 'POST':
        form = PlanejamentoForm(request.POST, instance=planejamento)
        if form.is_valid():
            form.save()
            return redirect('planejamento_list')
    else:
        form = PlanejamentoForm(instance=planejamento)

    return render(request, 'planejamento/planejamento_form.html', {'form': form})

def planejamento_delete(request, pk):
    planejamento = get_object_or_404(Planejamento, pk=pk)

    if request.method == 'POST':
        planejamento.delete()
        return redirect('planejamento_list')

    return render(request, 'planejamento/planejamento_confirm_delete.html', {'planejamento': planejamento})

def planejamento_detail(request, pk):
    planejamento = get_object_or_404(Planejamento, pk=pk)
    return render(request, 'planejamento/planejamento_detail.html', {'planejamento': planejamento})

templates/planejamento/planejamento_confirm_delete.html
{% extends 'base.html' %}

{% block page_title %}Confirmar Exclusão{% endblock %}

{% block breadcrumb %}
<ul class="app-breadcrumb breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base_page' %}"><i class="fa fa-home fa-lg"></i></a></li>
    <li class="breadcrumb-item"><a href="{% url 'planejamento_list' %}">Lista de Planejamentos</a></li>
    <li class="breadcrumb-item">Excluir Planejamento</li>
</ul>
{% endblock breadcrumb %}

{% block content %}
<div class="container">
    <h3>Tem certeza que deseja excluir "{{ planejamento.nome }}"?</h3>
    <p>Essa ação não pode ser desfeita.</p>
    
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
        <a class="btn btn-secondary" href="{% url 'planejamento_detail' planejamento.pk %}">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/planejamento/planejamento_detail.html
{% extends 'base.html' %}

{% block page_title %}Detalhes do Planejamento{% endblock %}

{% block breadcrumb %}
<ul class="app-breadcrumb breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base_page' %}"><i class="fa fa-home fa-lg"></i></a></li>
    <li class="breadcrumb-item"><a href="{% url 'planejamento_list' %}">Lista de Planejamentos</a></li>
    <li class="breadcrumb-item">Detalhes do Planejamento</li>
</ul>
{% endblock breadcrumb %}

{% block content %}
<div class="container">
    <h3>{{ planejamento.nome }}</h3>
    <ul>
        <li><strong>Data de Cadastro:</strong> {{ planejamento.data_cadastro }}</li>
        <li><strong>Última Atualização:</strong> {{ planejamento.data_atualizacao }}</li>
    </ul>
    
    <h4>Funções Associadas:</h4>
    <ul>
        {% for funcao in planejamento.funcoes.all %}
            <li>{{ funcao.nome }}</li>
        {% empty %}
            <li>Não há funções associadas.</li>
        {% endfor %}
    </ul>

    <div class="clearfix">
        <a class="btn btn-secondary" href="{% url 'planejamento_list' %}">Voltar</a>
        <a class="btn btn-warning" href="{% url 'planejamento_update' planejamento.pk %}">Editar</a>
        <a class="btn btn-danger" href="{% url 'planejamento_delete' planejamento.pk %}">Excluir</a>
    </div>
</div>
{% endblock %}

templates/planejamento/planejamento_form.html
{% extends 'base.html' %}

{% block page_title %}Adicionar/Editar Planejamento{% endblock %}

{% block breadcrumb %}
<ul class="app-breadcrumb breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base_page' %}"><i class="fa fa-home fa-lg"></i></a></li>
    <li class="breadcrumb-item"><a href="{% url 'planejamento_list' %}">Lista de Planejamentos</a></li>
    <li class="breadcrumb-item">Adicionar/Editar Planejamento</li>
</ul>
{% endblock breadcrumb %}

{% block content %}
<div class="container">
    <h3>{% if form.instance.pk %}Editar{% else %}Adicionar{% endif %} Planejamento</h3>

    <form method="POST">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="id_nome">Nome do Planejamento</label>
            {{ form.nome }}
        </div>

        <h4>Funções Associadas</h4>
        <div id="funcoes-container">
            {% for form_funcao in formset %}
                <div class="funcao-item">
                    {{ form_funcao.funcao }}
                    <button type="button" class="btn btn-danger remove-funcao">Remover</button>
                </div>
            {% endfor %}
        </div>

        <button type="button" id="add-funcao" class="btn btn-primary">Adicionar Função</button>

        <button type="submit" class="btn btn-success">Salvar</button>
        <a class="btn btn-secondary" href="{% url 'planejamento_list' %}">Cancelar</a>
    </form>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("add-funcao").addEventListener("click", function () {
            let container = document.getElementById("funcoes-container");
            let newElement = document.createElement("div");
            newElement.classList.add("funcao-item");
            newElement.innerHTML = `
                <select name="funcoes" class="form-control">
                    {% for funcao in funcoes_disponiveis %}
                        <option value="{{ funcao.id }}">{{ funcao.nome }}</option>
                    {% endfor %}
                </select>
                <button type="button" class="btn btn-danger remove-funcao">Remover</button>
            `;
            container.appendChild(newElement);

            newElement.querySelector(".remove-funcao").addEventListener("click", function () {
                newElement.remove();
            });
        });

        document.querySelectorAll(".remove-funcao").forEach(function (button) {
            button.addEventListener("click", function () {
                this.parentElement.remove();
            });
        });
    });
</script>
{% endblock %}

templates/planejamento/planejamento_list.html
{% extends 'base.html' %}

{% block page_title %}Planejamentos{% endblock %}

{% block content %}
<div class="container">
    <h3>Planejamentos</h3>
    <a class="btn btn-success mb-3" href="{% url 'planejamento_create' %}">Novo Planejamento</a>
    
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Data de Cadastro</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for planejamento in page_obj %}
            <tr>
                <td>{{ planejamento.nome }}</td>
                <td>{{ planejamento.data_cadastro }}</td>
                <td>
                    <a class="btn btn-info" href="{% url 'planejamento_detail' planejamento.pk %}">Detalhes</a>
                    <a class="btn btn-warning" href="{% url 'planejamento_update' planejamento.pk %}">Editar</a>
                    <a class="btn btn-danger" href="{% url 'planejamento_delete' planejamento.pk %}">Excluir</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3" class="text-center">Nenhum planejamento encontrado.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}